joint_state_controller:
  type: "joint_state_controller/JointStateController"
  publish_rate: 50

br_wheel_joint_velocity_controller:
  type: "velocity_controllers/JointVelocityController"
  joint: br_wheel_joint
  pid: {p: 2000.0, i: 10.0, d: 0.1}

bl_wheel_joint_velocity_controller:
  type: "velocity_controllers/JointVelocityController"
  joint: bl_wheel_joint
  pid: {p: 2000.0, i: 10.0, d: 0.1}

fl_wheel_joint_velocity_controller:
  type: "velocity_controllers/JointVelocityController"
  joint: fl_wheel_joint
  pid: {p: 2000.0, i: 10.0, d: 0.1}

fr_wheel_joint_velocity_controller:
  type: "velocity_controllers/JointVelocityController"
  joint: fr_wheel_joint
  pid: {p: 2000.0, i: 10.0, d: 0.1}

gazebo_ros_control:
  pid_gains:
    fl_wheel_joint: {p: 2000.0, i: 10.0, d: 0.1}
    bl_wheel_joint: {p: 2000.0, i: 10.0, d: 0.1}
    fr_wheel_joint: {p: 2000.0, i: 10.0, d: 0.1}
    br_wheel_joint: {p: 2000.0, i: 10.0, d: 0.1}
